base:
  project: activity_tracking_project
  random_state: 42
  target_col: activity

data_source:
  s3_source: data_given/activity_context_tracking_data.csv

load_data:
  raw_dataset_csv: data/raw/activity_context_tracking_data.csv

split_data:
  train_path: data/processed/train_activity.csv
  test_path: data/processed/test_activity.csv
  test_size: 0.2

estimators:
  KNeighborsClassifier:
    params:
      n_neighbors: 3 
model_dir: saved_models

reports:
  scores: reports/score.json
