name: activity-tracking
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python src/train_and_evaluate.py

          echo "## MODEL METRICS" > report.md
          cat reports/scores.json >> report.md
          echo "## Confusion Matrix" >> report.md
          cml-publish confusion_matrix.png --md >> report.md

          
          cml-send-comment report.md
